include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

.skip-phpmd-rule: &skip-phpmd-rule
  if: '$SKIP_PHPMD == "1"'
  when: never

.phpmd-base:
  stage: validate
  rules:
    - !reference [.opt-in-current-rule]
    - *skip-phpmd-rule
    - !reference [.php-files-exist-rule]
  needs:
    - composer
  before_script:
    - curl -fsSL https://phpmd.org/static/latest/phpmd.phar -o vendor/bin/phpmd
    - chmod +x vendor/bin/phpmd
  script:
    - php --version
    - vendor/bin/phpmd --version
    - vendor/bin/phpmd $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME gitlab $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.xml --exclude 'tests/*,**/tests/*' > phpmd-quality-report.json || true
    - vendor/bin/phpmd $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME text $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.phpmd.xml --exclude 'tests/*,**/tests/*'
  allow_failure: false
  artifacts:
    expose_as: phpmd
    when: always
    expire_in: 6 mos
    reports:
      codequality: phpmd-quality-report.json
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - phpmd-quality-report.json

.twig-lint-base:
  stage: validate
  before_script:
    - composer require --dev vincentlanglet/twig-cs-fixer
  script:
    - vendor/bin/twig-cs-fixer lint --config=$_WEB_ROOT/modules/custom/$CI_PROJECT_NAME/.twig-cs-fixer.php $_WEB_ROOT/modules/custom/$CI_PROJECT_NAME
  rules:
    - changes:
        - "**/*.twig"
    - if: '$CI_PIPELINE_SOURCE == "push"'
  allow_failure: false
  artifacts:
    expose_as: twig-lint
    when: always
    expire_in: 6 mos
    reports:
      codequality: twig-lint-quality-report.xml
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - twig-lint-quality-report.xml

.prettier-lint-base:
  stage: validate
  script:
    - echo "Prettier version $(${CI_PROJECT_DIR}/${_WEB_ROOT}/core/node_modules/.bin/prettier --version)"
    - ${CI_PROJECT_DIR}/${_WEB_ROOT}/core/node_modules/.bin/prettier --check ${CI_PROJECT_DIR}/docs/
  rules:
    - changes:
        - "docs/*.md"
        - "docs/**/*.md"
  allow_failure: false
  artifacts:
    expose_as: prettier-lint
    when: always
    expire_in: 6 mos
    reports:
      codequality: prettier-lint-quality-report.xml
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - prettier-lint-quality-report.xml

phpmd:
  extends: .phpmd-base
twig-lint:
  extends: .twig-lint-base
prettier-lint:
  extends: .prettier-lint-base
composer-lint:
  allow_failure: true
cspell:
  allow_failure: true
eslint:
  allow_failure: true
phpcs:
  allow_failure: true
phpstan:
  allow_failure: true
phpunit:
  allow_failure: true
  variables:
    _PHPUNIT_EXTRA: ''
