<?php

/**
 * @file
 * Logs user authentication in the admin_audit_trail module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\admin_audit_trail_auth\Hook\AdminAuditTrailAuthHooks;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
#[LegacyHook]
function admin_audit_trail_auth_admin_audit_trail_handlers() {
  return \Drupal::service(AdminAuditTrailAuthHooks::class)->adminAuditTrailHandlers();
}

/**
 * Event log callback for the user authentication event log.
 *
 * @return array|null
 *   Return an associative array of data to insert in database.
 */
function admin_audit_trail_auth_form_submit($form, $form_state, $form_id) {
  return \Drupal::service(AdminAuditTrailAuthHooks::class)->formSubmitCallback($form, $form_state, $form_id);
}

/**
 * Implements hook_user_logout().
 */
#[LegacyHook]
function admin_audit_trail_auth_user_logout($account) {
  \Drupal::service(AdminAuditTrailAuthHooks::class)->userLogout($account);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
#[LegacyHook]
function admin_audit_trail_auth_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service(AdminAuditTrailAuthHooks::class)->formUserLoginFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_user_login().
 */
#[LegacyHook]
function admin_audit_trail_auth_user_login($account) {
  \Drupal::service(AdminAuditTrailAuthHooks::class)->userLogin($account);
}

/**
 * Implements hook_form_FORM_ID_validate().
 */
function admin_audit_trail_auth_user_login_validate($form, &$form_state) {
  \Drupal::service(AdminAuditTrailAuthHooks::class)->userLoginValidate($form, $form_state);
}
