<?php

/**
 * @file
 * Logs block content CUD commands in the admin_audit_trail module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\admin_audit_trail_block_content\Hook\AdminAuditTrailBlockContentHooks;
use Drupal\block_content\BlockContentInterface;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
#[LegacyHook]
function admin_audit_trail_block_content_admin_audit_trail_handlers() {
  return \Drupal::service(AdminAuditTrailBlockContentHooks::class)->adminAuditTrailHandlers();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
#[LegacyHook]
function admin_audit_trail_block_content_block_content_insert(BlockContentInterface $entity) {
  \Drupal::service(AdminAuditTrailBlockContentHooks::class)->blockContentInsert($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
#[LegacyHook]
function admin_audit_trail_block_content_block_content_update(BlockContentInterface $entity) {
  \Drupal::service(AdminAuditTrailBlockContentHooks::class)->blockContentUpdate($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
#[LegacyHook]
function admin_audit_trail_block_content_block_content_delete(BlockContentInterface $entity) {
  \Drupal::service(AdminAuditTrailBlockContentHooks::class)->blockContentDelete($entity);
}
