<?php

/**
 * @file
 * Logs redirect CUD commands in the admin_audit_trail module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\admin_audit_trail_redirect\Hook\AdminAuditTrailRedirectHooks;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
#[LegacyHook]
function admin_audit_trail_redirect_admin_audit_trail_handlers() {
  return \Drupal::service(AdminAuditTrailRedirectHooks::class)->adminAuditTrailHandlers();
}

/**
 * Implements hook_redirect_insert().
 */
#[LegacyHook]
function admin_audit_trail_redirect_redirect_insert($redirect) {
  \Drupal::service(AdminAuditTrailRedirectHooks::class)->redirectInsert($redirect);
}

/**
 * Implements hook_redirect_update().
 */
#[LegacyHook]
function admin_audit_trail_redirect_redirect_update($redirect) {
  \Drupal::service(AdminAuditTrailRedirectHooks::class)->redirectUpdate($redirect);
}

/**
 * Implements hook_redirect_delete().
 */
#[LegacyHook]
function admin_audit_trail_redirect_redirect_delete($redirect) {
  \Drupal::service(AdminAuditTrailRedirectHooks::class)->redirectDelete($redirect);
}
