<?php

/**
 * @file
 * Logs workflows commands in the admin_audit_trail module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\admin_audit_trail_workflows\Hook\AdminAuditTrailWorkflowsHooks;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
#[LegacyHook]
function admin_audit_trail_workflows_admin_audit_trail_handlers() {
  return \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->adminAuditTrailHandlers();
}

/**
 * Implements hook_node_presave().
 */
#[LegacyHook]
function admin_audit_trail_workflows_node_presave($node) {
  \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->nodePresave($node);
}

/**
 * Implements hook_node_insert().
 */
#[LegacyHook]
function admin_audit_trail_workflows_node_insert($node) {
  \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->nodeInsert($node);
}

/**
 * Implements hook_node_update().
 */
#[LegacyHook]
function admin_audit_trail_workflows_node_update($node) {
  \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->nodeUpdate($node);
}
