<?php

/**
 * @file
 * Logs workflows commands in the admin_audit_trail module.
 */

use Drupal\admin_audit_trail_workflows\Hook\AdminAuditTrailWorkflowsHooks;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
#[LegacyHook]
function admin_audit_trail_workflows_admin_audit_trail_handlers() {
  return \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->adminAuditTrailHandlers();
}

/**
 * Implements hook_entity_presave().
 */
#[LegacyHook]
function admin_audit_trail_workflows_entity_presave(EntityInterface $entity) {
  \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->entityPresave($entity);
}

/**
 * Implements hook_entity_insert().
 */
#[LegacyHook]
function admin_audit_trail_workflows_entity_insert(EntityInterface $entity) {
  \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->entityInsert($entity);
}

/**
 * Implements hook_entity_update().
 */
#[LegacyHook]
function admin_audit_trail_workflows_entity_update(EntityInterface $entity) {
  \Drupal::service(AdminAuditTrailWorkflowsHooks::class)->entityUpdate($entity);
}
