<?php

/**
 * @file
 * Logs user CUD commands in the admin_audit_trail module.
 */

/**
 * Implements hook_admin_audit_trail_handlers().
 */
function admin_audit_trail_group_admin_audit_trail_handlers() {
  // User event log handler.
  $handlers = [];
  $handlers['group'] = [
    'title' => t('Group'),
  ];
  return $handlers;
}

/**
 * Implements hook_group_insert().
 */
function admin_audit_trail_group_group_insert($group) {
  $log = [
    'type' => 'group',
    'operation' => 'insert',
    'description' => t('%bundle: %title', [
      '%bundle' => $group->bundle(),
      '%title' => $group->label(),
    ]),
    'ref_numeric' => $group->id(),
    'ref_char' => $group->label(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_group_update().
 */
function admin_audit_trail_group_group_update($group) {
  $log = [
    'type' => 'group',
    'operation' => 'update',
    'description' => t('%bundle: %title', [
      '%bundle' => $group->bundle(),
      '%title' => $group->label(),
    ]),
    'ref_numeric' => $group->id(),
    'ref_char' => $group->label(),
  ];
  admin_audit_trail_insert($log);
}

/**
 * Implements hook_group_delete().
 */
function admin_audit_trail_group_group_delete($group) {
  $log = [
    'type' => 'group',
    'operation' => 'delete',
    'description' => t('%bundle: %title', [
      '%bundle' => $group->bundle(),
      '%title' => $group->label(),
    ]),
    'ref_numeric' => $group->id(),
    'ref_char' => $group->label(),
  ];
  admin_audit_trail_insert($log);
}
