<?php

/**
 * @file
 * Logs menu CUD commands in the admin_audit_trail module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\admin_audit_trail_taxonomy\Hook\AdminAuditTrailTaxonomyHooks;

/**
 * Implements hook_admin_audit_trail_handlers().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_admin_audit_trail_handlers() {
  return \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->adminAuditTrailHandlers();
}

/**
 * Implements hook_taxonomy_vocabulary_insert().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_taxonomy_vocabulary_insert($vocabulary) {
  \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->taxonomyVocabularyInsert($vocabulary);
}

/**
 * Implements hook_taxonomy_vocabulary_update().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_taxonomy_vocabulary_update($vocabulary) {
  \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->taxonomyVocabularyUpdate($vocabulary);
}

/**
 * Implements hook_taxonomy_vocabulary_delete().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_taxonomy_vocabulary_delete($vocabulary) {
  \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->taxonomyVocabularyDelete($vocabulary);
}

/**
 * Implements hook_taxonomy_term_insert().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_taxonomy_term_insert($term) {
  \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->taxonomyTermInsert($term);
}

/**
 * Implements hook_taxonomy_term_update().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_taxonomy_term_update($term) {
  \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->taxonomyTermUpdate($term);
}

/**
 * Implements hook_taxonomy_term_delete().
 */
#[LegacyHook]
function admin_audit_trail_taxonomy_taxonomy_term_delete($term) {
  \Drupal::service(AdminAuditTrailTaxonomyHooks::class)->taxonomyTermDelete($term);
}
